### ISSUE TITLE
typos in the configuration example

### ISSUE THREAD

**Issue by philipthor** [boghammar/MMM-CrisisInformationSweden#2]
missing comma on the second row

`position: 'top_right'`

too many commas on the last row

`oldest: 7, `

**Comment by boghammar** [comment]
Thanks, great help to find these small errors. Some people use the example configuration and the files issues that are hard to track due to a faulty configuration. I'll fix it in a minute.

**Comment by boghammar** [comment]
So then that's fixed :)

Cheers
