### ISSUE TITLE
"oldest" in config seems not working

### ISSUE THREAD

**Issue by acejacek** [boghammar/MMM-CrisisInformationSweden#3]
I have default config with `oldest: 7`, but I see warnings which are 10 days old.

**Comment by boghammar** [comment]
Ok, I'll have a look and see what goes wrong.

**Comment by boghammar** [comment]
It was a problem when there only was one feed that was within the 'oldest' time limit. It should be fixed now. Please test and feedback with a new issue if not solved, closing this one now.
Cheers

**Comment by acejacek** [comment]
Works. Thanks for fixing it.
