### ISSUE TITLE
"oldest" in config not working if shorter than message age

### ISSUE THREAD

**Issue by mrkalle** [boghammar/MMM-CrisisInformationSweden#6]
Set "oldest" config to "3".

Load page: At first the correct text "There are no messages younger than 3 days" shows.

![image](https://user-images.githubusercontent.com/1117559/38190739-e3604eba-3665-11e8-8839-7b5001b2348d.png)

At next uiUpdateInterval (10s): A message with age 6 days are shown. 

![image](https://user-images.githubusercontent.com/1117559/38190648-82bd0224-3665-11e8-987c-1f69277080cd.png)

Current time: 2018-04-02 11:04.
Current feed:

{
  "Entries": [
    {
      "ID": "http://api.krisinformation.se/v1/capmessage/10572?format=xml",
      "Updated": "2018-03-28T07:02:00+02:00",
      "Published": "2018-03-27T22:13:38+02:00",
      "CapEvent": "News",
      "Author": {
        "Name": "https://www.krisinformation.se/"
      },
      "Title": "Viktigt meddelande till allmänheten i Kalmar",
      "Link": {
        "Id": null,
        "LinkName": null,
        "LinkUrl": "http://api.krisinformation.se/v1/capmessage/10572?format=xml"
      },
      "Summary": "Det viktiga meddelande till allmänheten som utfärdades för Kalmar gäller inte längre. Faran är över. Det brann i en industrilokal på Engelska vägen i Kalmar med kraftig rökutveckling som följd. Räddningsledaren uppmanade alla i området att gå inomhus och stänga dörrar, fönster och ventilation. ",
      "CapArea": [
        {
          "CapAreaDesc": "Kalmar län",
          "Coordinate": "16.4380172241515,57.1227021283545 0"
        },
        {
          "CapAreaDesc": "Kalmar",
          "Coordinate": "16.366667,56.666667 0"
        }
      ]
    },
    {
      "ID": "http://api.krisinformation.se/v1/capmessage/10569?format=xml",
      "Updated": "2018-03-22T16:43:11+01:00",
      "Published": "2018-03-22T16:37:54+01:00",
      "CapEvent": "News",
      "Author": {
        "Name": "https://www.krisinformation.se/"
      },
      "Title": "Viktigt meddelande till allmänheten i Åsele",
      "Link": {
        "Id": null,
        "LinkName": null,
        "LinkUrl": "http://api.krisinformation.se/v1/capmessage/10569?format=xml"
      },
      "Summary": "Det viktiga meddelande till allmänheten som utfärdades för Åsele i Västerbotten gäller inte längre. Faran är över. En brand med kraftig rökutveckling gjorde att räddningsledaren uppmanade alla i området att gå inomhus och stänga fönster, dörrar och ventilation. Detta på grund av en brand med kraftig rökutveckling.",
      "CapArea": [
        {
          "CapAreaDesc": "Västerbottens län",
          "Coordinate": "18.1865376130758,64.7640174021215 0"
        },
        {
          "CapAreaDesc": "Åsele",
          "Coordinate": "17.35,64.15 0"
        }
      ]
    }
  ]
}

**Comment by boghammar** [comment]
Yeah, that code around _oldest_ is a bit messy,have to look at it again. 

Thanks for the report.

**Comment by boghammar** [comment]
It was a dumb mistake easy to fix. Don't know how I missed that. Thanks again.

Please try now with the latest checked in on master.

**Comment by boghammar** [comment]
Works for me so I'm closing this issue now.
