### ISSUE TITLE
No space when no messages

### ISSUE THREAD

**Issue by dberntsson** [boghammar/MMM-CrisisInformationSweden#7]
Most of the time I have the text "There are no messages younger than X days" presented on my screen.

I would like the area to be empty and available for other widgets if there are no information to present.

**Comment by boghammar** [comment]
This has been fixed in v1.2 with a new config parameter **silent**. By default it will show the message but if set to true no message is shown.

**Comment by dberntsson** [comment]
Works perfectly! Thanks
