### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by ChrisAcrobat** [boghammar/MMM-CrisisInformationSweden#8]
How ever I configure CrisisInformationSweden, the only thing I get is an entire black (full) screen. I guess that it is probably me that has done something wrong, but I can not figure out what? I am only getting this with CrisisInformationSweden and it diapers when I remove it from the config file.
I have followed the steps with first clone and then `npm install`. Current [config](https://github.com/boghammar/MMM-CrisisInformationSweden/files/3937959/config.js.txt) at the time of writing.

Thanks for the help.

**Comment by ChrisAcrobat** [comment]
[This](https://github.com/MichMich/MagicMirror/issues/1764) was apparently my problem. I have no idea how it happened.

**Comment by boghammar** [comment]
Good that you found the problem ;)
